// Mocks generated by Mockito 5.4.6 from annotations
// in gym_tracker/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:gym_tracker/core/enums.dart' as _i8;
import 'package:gym_tracker/data/db/app_database.dart' as _i2;
import 'package:gym_tracker/data/repositories/workout_repository.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _Fake$ExercisesTable_0 extends _i1.SmartFake
    implements _i2.$ExercisesTable {
  _Fake$ExercisesTable_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$WorkoutsTable_1 extends _i1.SmartFake
    implements _i2.$WorkoutsTable {
  _Fake$WorkoutsTable_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$WorkoutExercisesTable_2 extends _i1.SmartFake
    implements _i2.$WorkoutExercisesTable {
  _Fake$WorkoutExercisesTable_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$SetEntriesTable_3 extends _i1.SmartFake
    implements _i2.$SetEntriesTable {
  _Fake$SetEntriesTable_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$TemplatesTable_4 extends _i1.SmartFake
    implements _i2.$TemplatesTable {
  _Fake$TemplatesTable_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$TemplateExercisesTable_5 extends _i1.SmartFake
    implements _i2.$TemplateExercisesTable {
  _Fake$TemplateExercisesTable_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AppDatabaseManager_6 extends _i1.SmartFake
    implements _i2.$AppDatabaseManager {
  _Fake$AppDatabaseManager_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedDatabase_7 extends _i1.SmartFake
    implements _i3.GeneratedDatabase {
  _FakeGeneratedDatabase_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriftDatabaseOptions_8 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrationStrategy_9 extends _i1.SmartFake
    implements _i3.MigrationStrategy {
  _FakeMigrationStrategy_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryUpdateRules_10 extends _i1.SmartFake
    implements _i3.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnection_11 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryExecutor_12 extends _i1.SmartFake implements _i3.QueryExecutor {
  _FakeQueryExecutor_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryStore_13 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnectionUser_14 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrator_15 extends _i1.SmartFake implements _i3.Migrator {
  _FakeMigrator_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_16<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsertStatement_17<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.InsertStatement<T1, D1> {
  _FakeInsertStatement_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStatement_18<T extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.UpdateStatement<T, D> {
  _FakeUpdateStatement_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSimpleSelectStatement_19<T1 extends _i3.HasResultSet, D>
    extends _i1.SmartFake implements _i3.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJoinedSelectStatement_20<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseSelectStatement_21<Row> extends _i1.SmartFake
    implements _i3.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteStatement_22<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectable_23<T> extends _i1.SmartFake implements _i3.Selectable<T> {
  _FakeSelectable_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerationContext_24 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppDatabase_25 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkoutWithDetails_26 extends _i1.SmartFake
    implements _i6.WorkoutWithDetails {
  _FakeWorkoutWithDetails_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i2.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion => (super.noSuchMethod(
        Invocation.getter(#schemaVersion),
        returnValue: 0,
      ) as int);

  @override
  _i2.$ExercisesTable get exercises => (super.noSuchMethod(
        Invocation.getter(#exercises),
        returnValue: _Fake$ExercisesTable_0(
          this,
          Invocation.getter(#exercises),
        ),
      ) as _i2.$ExercisesTable);

  @override
  _i2.$WorkoutsTable get workouts => (super.noSuchMethod(
        Invocation.getter(#workouts),
        returnValue: _Fake$WorkoutsTable_1(
          this,
          Invocation.getter(#workouts),
        ),
      ) as _i2.$WorkoutsTable);

  @override
  _i2.$WorkoutExercisesTable get workoutExercises => (super.noSuchMethod(
        Invocation.getter(#workoutExercises),
        returnValue: _Fake$WorkoutExercisesTable_2(
          this,
          Invocation.getter(#workoutExercises),
        ),
      ) as _i2.$WorkoutExercisesTable);

  @override
  _i2.$SetEntriesTable get setEntries => (super.noSuchMethod(
        Invocation.getter(#setEntries),
        returnValue: _Fake$SetEntriesTable_3(
          this,
          Invocation.getter(#setEntries),
        ),
      ) as _i2.$SetEntriesTable);

  @override
  _i2.$TemplatesTable get templates => (super.noSuchMethod(
        Invocation.getter(#templates),
        returnValue: _Fake$TemplatesTable_4(
          this,
          Invocation.getter(#templates),
        ),
      ) as _i2.$TemplatesTable);

  @override
  _i2.$TemplateExercisesTable get templateExercises => (super.noSuchMethod(
        Invocation.getter(#templateExercises),
        returnValue: _Fake$TemplateExercisesTable_5(
          this,
          Invocation.getter(#templateExercises),
        ),
      ) as _i2.$TemplateExercisesTable);

  @override
  _i2.$AppDatabaseManager get managers => (super.noSuchMethod(
        Invocation.getter(#managers),
        returnValue: _Fake$AppDatabaseManager_6(
          this,
          Invocation.getter(#managers),
        ),
      ) as _i2.$AppDatabaseManager);

  @override
  Iterable<_i3.TableInfo<_i3.Table, Object?>> get allTables =>
      (super.noSuchMethod(
        Invocation.getter(#allTables),
        returnValue: <_i3.TableInfo<_i3.Table, Object?>>[],
      ) as Iterable<_i3.TableInfo<_i3.Table, Object?>>);

  @override
  List<_i3.DatabaseSchemaEntity> get allSchemaEntities => (super.noSuchMethod(
        Invocation.getter(#allSchemaEntities),
        returnValue: <_i3.DatabaseSchemaEntity>[],
      ) as List<_i3.DatabaseSchemaEntity>);

  @override
  _i3.GeneratedDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeGeneratedDatabase_7(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i3.GeneratedDatabase);

  @override
  _i3.DriftDatabaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeDriftDatabaseOptions_8(
          this,
          Invocation.getter(#options),
        ),
      ) as _i3.DriftDatabaseOptions);

  @override
  _i3.MigrationStrategy get migration => (super.noSuchMethod(
        Invocation.getter(#migration),
        returnValue: _FakeMigrationStrategy_9(
          this,
          Invocation.getter(#migration),
        ),
      ) as _i3.MigrationStrategy);

  @override
  _i3.StreamQueryUpdateRules get streamUpdateRules => (super.noSuchMethod(
        Invocation.getter(#streamUpdateRules),
        returnValue: _FakeStreamQueryUpdateRules_10(
          this,
          Invocation.getter(#streamUpdateRules),
        ),
      ) as _i3.StreamQueryUpdateRules);

  @override
  _i3.DatabaseConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeDatabaseConnection_11(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i3.DatabaseConnection);

  @override
  _i3.SqlTypes get typeMapping => (super.noSuchMethod(
        Invocation.getter(#typeMapping),
        returnValue: _i7.dummyValue<_i3.SqlTypes>(
          this,
          Invocation.getter(#typeMapping),
        ),
      ) as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeQueryExecutor_12(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i3.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries => (super.noSuchMethod(
        Invocation.getter(#streamQueries),
        returnValue: _FakeStreamQueryStore_13(
          this,
          Invocation.getter(#streamQueries),
        ),
      ) as _i4.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
        Invocation.getter(#resolvedEngine),
        returnValue: _FakeDatabaseConnectionUser_14(
          this,
          Invocation.getter(#resolvedEngine),
        ),
      ) as _i3.DatabaseConnectionUser);

  @override
  _i5.Future<_i2.Workout?> getWorkoutById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getWorkoutById,
          [id],
        ),
        returnValue: _i5.Future<_i2.Workout?>.value(),
      ) as _i5.Future<_i2.Workout?>);

  @override
  _i5.Future<_i2.Exercise?> getExerciseById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getExerciseById,
          [id],
        ),
        returnValue: _i5.Future<_i2.Exercise?>.value(),
      ) as _i5.Future<_i2.Exercise?>);

  @override
  _i5.Future<_i2.WorkoutExercise?> getWorkoutExerciseById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutExerciseById,
          [id],
        ),
        returnValue: _i5.Future<_i2.WorkoutExercise?>.value(),
      ) as _i5.Future<_i2.WorkoutExercise?>);

  @override
  _i5.Future<List<_i2.Exercise>> getAllExercises() => (super.noSuchMethod(
        Invocation.method(
          #getAllExercises,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Exercise>>.value(<_i2.Exercise>[]),
      ) as _i5.Future<List<_i2.Exercise>>);

  @override
  _i5.Future<List<_i2.Workout>> listWorkoutsDesc() => (super.noSuchMethod(
        Invocation.method(
          #listWorkoutsDesc,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Workout>>.value(<_i2.Workout>[]),
      ) as _i5.Future<List<_i2.Workout>>);

  @override
  _i5.Future<List<_i2.Workout>> listActiveWorkoutsDesc() => (super.noSuchMethod(
        Invocation.method(
          #listActiveWorkoutsDesc,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Workout>>.value(<_i2.Workout>[]),
      ) as _i5.Future<List<_i2.Workout>>);

  @override
  _i5.Future<List<_i2.WorkoutExercise>> listWorkoutExercises(
          String? workoutId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listWorkoutExercises,
          [workoutId],
        ),
        returnValue: _i5.Future<List<_i2.WorkoutExercise>>.value(
            <_i2.WorkoutExercise>[]),
      ) as _i5.Future<List<_i2.WorkoutExercise>>);

  @override
  _i5.Future<List<_i2.SetEntry>> listSets(String? workoutExerciseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listSets,
          [workoutExerciseId],
        ),
        returnValue: _i5.Future<List<_i2.SetEntry>>.value(<_i2.SetEntry>[]),
      ) as _i5.Future<List<_i2.SetEntry>>);

  @override
  _i5.Future<List<_i2.Template>> listTemplates() => (super.noSuchMethod(
        Invocation.method(
          #listTemplates,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Template>>.value(<_i2.Template>[]),
      ) as _i5.Future<List<_i2.Template>>);

  @override
  _i5.Future<_i2.Template?> getTemplateById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTemplateById,
          [id],
        ),
        returnValue: _i5.Future<_i2.Template?>.value(),
      ) as _i5.Future<_i2.Template?>);

  @override
  _i5.Future<List<_i2.TemplateExercise>> listTemplateExercises(
          String? templateId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listTemplateExercises,
          [templateId],
        ),
        returnValue: _i5.Future<List<_i2.TemplateExercise>>.value(
            <_i2.TemplateExercise>[]),
      ) as _i5.Future<List<_i2.TemplateExercise>>);

  @override
  _i5.Future<void> insertExercise(_i2.ExercisesCompanion? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertExercise,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> createWorkout({
    required String? id,
    required DateTime? date,
    String? title,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorkout,
          [],
          {
            #id: id,
            #date: date,
            #title: title,
            #notes: notes,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createWorkout,
            [],
            {
              #id: id,
              #date: date,
              #title: title,
              #notes: notes,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Stream<List<_i2.Workout>> watchActiveWorkoutsDesc() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchActiveWorkoutsDesc,
          [],
        ),
        returnValue: _i5.Stream<List<_i2.Workout>>.empty(),
      ) as _i5.Stream<List<_i2.Workout>>);

  @override
  _i5.Future<void> setWorkoutDone(
    String? workoutId,
    bool? done,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setWorkoutDone,
          [
            workoutId,
            done,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> addExerciseToWorkout({
    required String? id,
    required String? workoutId,
    required String? exerciseId,
    required int? ord,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addExerciseToWorkout,
          [],
          {
            #id: id,
            #workoutId: workoutId,
            #exerciseId: exerciseId,
            #ord: ord,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #addExerciseToWorkout,
            [],
            {
              #id: id,
              #workoutId: workoutId,
              #exerciseId: exerciseId,
              #ord: ord,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> updateWorkoutExerciseOrder({
    required String? workoutExerciseId,
    required int? ord,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkoutExerciseOrder,
          [],
          {
            #workoutExerciseId: workoutExerciseId,
            #ord: ord,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setWorkoutExerciseDone({
    required String? workoutExerciseId,
    required bool? done,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setWorkoutExerciseDone,
          [],
          {
            #workoutExerciseId: workoutExerciseId,
            #done: done,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addSet({
    required String? id,
    required String? workoutExerciseId,
    required int? setIndex,
    required int? reps,
    required double? weight,
    double? rpe,
    int? restSec,
    String? note,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSet,
          [],
          {
            #id: id,
            #workoutExerciseId: workoutExerciseId,
            #setIndex: setIndex,
            #reps: reps,
            #weight: weight,
            #rpe: rpe,
            #restSec: restSec,
            #note: note,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> createTemplate({
    required String? id,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTemplate,
          [],
          {
            #id: id,
            #name: name,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createTemplate,
            [],
            {
              #id: id,
              #name: name,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> addTemplateExercise({
    required String? id,
    required String? templateId,
    required String? exerciseId,
    required int? ord,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTemplateExercise,
          [],
          {
            #id: id,
            #templateId: templateId,
            #exerciseId: exerciseId,
            #ord: ord,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> countWorkoutsThisMonth() => (super.noSuchMethod(
        Invocation.method(
          #countWorkoutsThisMonth,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> getTrainingStreak() => (super.noSuchMethod(
        Invocation.method(
          #getTrainingStreak,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> countExercisesThisMonth() => (super.noSuchMethod(
        Invocation.method(
          #countExercisesThisMonth,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.Workout>> listFinishedWorkoutsBetweenDesc({
    required int? startEpoch,
    required int? endEpoch,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listFinishedWorkoutsBetweenDesc,
          [],
          {
            #startEpoch: startEpoch,
            #endEpoch: endEpoch,
          },
        ),
        returnValue: _i5.Future<List<_i2.Workout>>.value(<_i2.Workout>[]),
      ) as _i5.Future<List<_i2.Workout>>);

  @override
  _i5.Future<int> countExercisesInWorkout(String? workoutId) =>
      (super.noSuchMethod(
        Invocation.method(
          #countExercisesInWorkout,
          [workoutId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> countSetsInWorkout(String? workoutId) => (super.noSuchMethod(
        Invocation.method(
          #countSetsInWorkout,
          [workoutId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> updateSetNote({
    required String? setId,
    String? note,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSetNote,
          [],
          {
            #setId: setId,
            #note: note,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  ({int endEpoch, int startEpoch}) monthBounds(DateTime? now) =>
      (super.noSuchMethod(
        Invocation.method(
          #monthBounds,
          [now],
        ),
        returnValue: (endEpoch: 0, startEpoch: 0),
      ) as ({int endEpoch, int startEpoch}));

  @override
  _i5.Future<void> deleteSet(String? setId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSet,
          [setId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteWorkoutExercise(String? workoutExerciseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWorkoutExercise,
          [workoutExerciseId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> createExercise({
    required String? name,
    required String? muscleGroup,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createExercise,
          [],
          {
            #name: name,
            #muscleGroup: muscleGroup,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createExercise,
            [],
            {
              #name: name,
              #muscleGroup: muscleGroup,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i3.Migrator createMigrator() => (super.noSuchMethod(
        Invocation.method(
          #createMigrator,
          [],
        ),
        returnValue: _FakeMigrator_15(
          this,
          Invocation.method(
            #createMigrator,
            [],
          ),
        ),
      ) as _i3.Migrator);

  @override
  _i5.Future<void> beforeOpen(
    _i3.QueryExecutor? executor,
    _i3.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #beforeOpen,
          [
            executor,
            details,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
          _i4.QueryStreamFetcher<T>? stmt) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [stmt],
        ),
        returnValue: _i5.Stream<T>.empty(),
      ) as _i5.Stream<T>);

  @override
  T alias<T, D>(
    _i3.ResultSetImplementation<T, D>? table,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #alias,
          [
            table,
            alias,
          ],
        ),
        returnValue: _i7.dummyValue<T>(
          this,
          Invocation.method(
            #alias,
            [
              table,
              alias,
            ],
          ),
        ),
      ) as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(
          #markTablesUpdated,
          [tables],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(
          #notifyUpdates,
          [updates],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Stream<Set<_i3.TableUpdate>> tableUpdates(
          [_i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(
        Invocation.method(
          #tableUpdates,
          [query],
        ),
        returnValue: _i5.Stream<Set<_i3.TableUpdate>>.empty(),
      ) as _i5.Stream<Set<_i3.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
          _i5.FutureOr<T> Function(_i3.QueryExecutor)? fn) =>
      (super.noSuchMethod(
        Invocation.method(
          #doWhenOpened,
          [fn],
        ),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #doWhenOpened,
                  [fn],
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_16<T>(
              this,
              Invocation.method(
                #doWhenOpened,
                [fn],
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
          _i3.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #into,
          [table],
        ),
        returnValue: _FakeInsertStatement_17<T, D>(
          this,
          Invocation.method(
            #into,
            [table],
          ),
        ),
      ) as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
          _i3.TableInfo<Tbl, R>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [table],
        ),
        returnValue: _FakeUpdateStatement_18<Tbl, R>(
          this,
          Invocation.method(
            #update,
            [table],
          ),
        ),
      ) as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeSimpleSelectStatement_19<T, R>(
          this,
          Invocation.method(
            #select,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectOnly,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeJoinedSelectStatement_20<T, R>(
          this,
          Invocation.method(
            #selectOnly,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
          Iterable<_i3.Expression<Object>>? columns) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectExpressions,
          [columns],
        ),
        returnValue: _FakeBaseSelectStatement_21<_i3.TypedResult>(
          this,
          Invocation.method(
            #selectExpressions,
            [columns],
          ),
        ),
      ) as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
          _i3.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakeDeleteStatement_22<T, D>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i3.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customUpdate,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customInsert,
          [query],
          {
            #variables: variables,
            #updates: updates,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customWriteReturning,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i5.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
      ) as _i5.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelect,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_23<_i3.QueryRow>(
          this,
          Invocation.method(
            #customSelect,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelectQuery,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_23<_i3.QueryRow>(
          this,
          Invocation.method(
            #customSelectQuery,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i3.Selectable<_i3.QueryRow>);

  @override
  _i5.Future<void> customStatement(
    String? statement, [
    List<dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customStatement,
          [
            statement,
            args,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#requireNew: requireNew},
        ),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#requireNew: requireNew},
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_16<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#requireNew: requireNew},
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #exclusively,
          [action],
        ),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #exclusively,
                  [action],
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_16<T>(
              this,
              Invocation.method(
                #exclusively,
                [action],
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(
          #batch,
          [runInBatch],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runWithInterceptor,
          [action],
          {#interceptor: interceptor},
        ),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #runWithInterceptor,
                  [action],
                  {#interceptor: interceptor},
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_16<T>(
              this,
              Invocation.method(
                #runWithInterceptor,
                [action],
                {#interceptor: interceptor},
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$write,
          [component],
          {
            #hasMultipleTables: hasMultipleTables,
            #startIndex: startIndex,
          },
        ),
        returnValue: _FakeGenerationContext_24(
          this,
          Invocation.method(
            #$write,
            [component],
            {
              #hasMultipleTables: hasMultipleTables,
              #startIndex: startIndex,
            },
          ),
        ),
      ) as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeInsertable,
          [
            table,
            insertable,
          ],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_24(
          this,
          Invocation.method(
            #$writeInsertable,
            [
              table,
              insertable,
            ],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i3.GenerationContext);

  @override
  String $expandVar(
    int? start,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$expandVar,
          [
            start,
            amount,
          ],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #$expandVar,
            [
              start,
              amount,
            ],
          ),
        ),
      ) as String);
}

/// A class which mocks [WorkoutRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutRepository extends _i1.Mock implements _i6.WorkoutRepository {
  MockWorkoutRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeAppDatabase_25(
          this,
          Invocation.getter(#db),
        ),
      ) as _i2.AppDatabase);

  @override
  _i5.Future<void> ensureSeed() => (super.noSuchMethod(
        Invocation.method(
          #ensureSeed,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Exercise>> allExercises() => (super.noSuchMethod(
        Invocation.method(
          #allExercises,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Exercise>>.value(<_i2.Exercise>[]),
      ) as _i5.Future<List<_i2.Exercise>>);

  @override
  _i5.Future<_i2.Exercise?> getExercise(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getExercise,
          [id],
        ),
        returnValue: _i5.Future<_i2.Exercise?>.value(),
      ) as _i5.Future<_i2.Exercise?>);

  @override
  _i5.Future<String> createCustomExercise({
    required String? name,
    required _i8.MuscleGroup? muscle,
    String? equipment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCustomExercise,
          [],
          {
            #name: name,
            #muscle: muscle,
            #equipment: equipment,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createCustomExercise,
            [],
            {
              #name: name,
              #muscle: muscle,
              #equipment: equipment,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> createExercise({
    required String? name,
    required String? muscleGroup,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createExercise,
          [],
          {
            #name: name,
            #muscleGroup: muscleGroup,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createExercise,
            [],
            {
              #name: name,
              #muscleGroup: muscleGroup,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> createWorkout({String? title}) => (super.noSuchMethod(
        Invocation.method(
          #createWorkout,
          [],
          {#title: title},
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createWorkout,
            [],
            {#title: title},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> createEmptyWorkoutNow({String? title}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEmptyWorkoutNow,
          [],
          {#title: title},
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createEmptyWorkoutNow,
            [],
            {#title: title},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> createWorkoutAt({
    required DateTime? date,
    String? title,
    bool? done = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorkoutAt,
          [],
          {
            #date: date,
            #title: title,
            #done: done,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createWorkoutAt,
            [],
            {
              #date: date,
              #title: title,
              #done: done,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i2.Workout?> getWorkout(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getWorkout,
          [id],
        ),
        returnValue: _i5.Future<_i2.Workout?>.value(),
      ) as _i5.Future<_i2.Workout?>);

  @override
  _i5.Future<void> markDone(
    String? workoutId,
    bool? done,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markDone,
          [
            workoutId,
            done,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Workout>> listWorkouts() => (super.noSuchMethod(
        Invocation.method(
          #listWorkouts,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Workout>>.value(<_i2.Workout>[]),
      ) as _i5.Future<List<_i2.Workout>>);

  @override
  _i5.Future<List<_i2.Workout>> listActiveWorkouts() => (super.noSuchMethod(
        Invocation.method(
          #listActiveWorkouts,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Workout>>.value(<_i2.Workout>[]),
      ) as _i5.Future<List<_i2.Workout>>);

  @override
  _i5.Stream<List<_i2.Workout>> watchActiveWorkouts() => (super.noSuchMethod(
        Invocation.method(
          #watchActiveWorkouts,
          [],
        ),
        returnValue: _i5.Stream<List<_i2.Workout>>.empty(),
      ) as _i5.Stream<List<_i2.Workout>>);

  @override
  _i5.Future<void> updateWorkoutDate(
    String? workoutId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkoutDate,
          [
            workoutId,
            date,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateWorkoutMeta(
    String? workoutId, {
    bool? done,
    String? title,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkoutMeta,
          [workoutId],
          {
            #done: done,
            #title: title,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> addExerciseToWorkout({
    required String? workoutId,
    required String? exerciseId,
    required int? ord,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addExerciseToWorkout,
          [],
          {
            #workoutId: workoutId,
            #exerciseId: exerciseId,
            #ord: ord,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #addExerciseToWorkout,
            [],
            {
              #workoutId: workoutId,
              #exerciseId: exerciseId,
              #ord: ord,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> addExerciseAtEnd(
    String? workoutId,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addExerciseAtEnd,
          [
            workoutId,
            exerciseId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.WorkoutExercise>> listWorkoutExercises(
          String? workoutId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listWorkoutExercises,
          [workoutId],
        ),
        returnValue: _i5.Future<List<_i2.WorkoutExercise>>.value(
            <_i2.WorkoutExercise>[]),
      ) as _i5.Future<List<_i2.WorkoutExercise>>);

  @override
  _i5.Future<void> setExerciseDone(
    String? workoutExerciseId,
    bool? done,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setExerciseDone,
          [
            workoutExerciseId,
            done,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> reorderExercises(List<_i2.WorkoutExercise>? ordered) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderExercises,
          [ordered],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteWorkoutExercise(String? workoutExerciseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWorkoutExercise,
          [workoutExerciseId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.SetEntry>> listSets(String? workoutExerciseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listSets,
          [workoutExerciseId],
        ),
        returnValue: _i5.Future<List<_i2.SetEntry>>.value(<_i2.SetEntry>[]),
      ) as _i5.Future<List<_i2.SetEntry>>);

  @override
  _i5.Future<void> addSetQuick({
    required String? workoutExerciseId,
    required int? reps,
    required double? weight,
    double? rpe,
    int? restSec,
    String? note,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSetQuick,
          [],
          {
            #workoutExerciseId: workoutExerciseId,
            #reps: reps,
            #weight: weight,
            #rpe: rpe,
            #restSec: restSec,
            #note: note,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteSet(String? setId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSet,
          [setId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateSetNote(
    String? setId,
    String? note,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSetNote,
          [
            setId,
            note,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<double> computeWorkoutVolume(String? workoutId) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeWorkoutVolume,
          [workoutId],
        ),
        returnValue: _i5.Future<double>.value(0.0),
      ) as _i5.Future<double>);

  @override
  _i5.Future<int> countWorkoutsThisMonth() => (super.noSuchMethod(
        Invocation.method(
          #countWorkoutsThisMonth,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> getTrainingStreak() => (super.noSuchMethod(
        Invocation.method(
          #getTrainingStreak,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> countExercisesThisMonth() => (super.noSuchMethod(
        Invocation.method(
          #countExercisesThisMonth,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> countExercisesInWorkout(String? workoutId) =>
      (super.noSuchMethod(
        Invocation.method(
          #countExercisesInWorkout,
          [workoutId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> countSetsInWorkout(String? workoutId) => (super.noSuchMethod(
        Invocation.method(
          #countSetsInWorkout,
          [workoutId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  ({int endEpoch, int startEpoch}) monthBounds(DateTime? now) =>
      (super.noSuchMethod(
        Invocation.method(
          #monthBounds,
          [now],
        ),
        returnValue: (endEpoch: 0, startEpoch: 0),
      ) as ({int endEpoch, int startEpoch}));

  @override
  _i5.Future<List<_i2.Workout>> listFinishedWorkoutsBetween({
    required DateTime? start,
    required DateTime? end,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listFinishedWorkoutsBetween,
          [],
          {
            #start: start,
            #end: end,
          },
        ),
        returnValue: _i5.Future<List<_i2.Workout>>.value(<_i2.Workout>[]),
      ) as _i5.Future<List<_i2.Workout>>);

  @override
  _i5.Future<List<({DateTime day, int volume})>> dailyVolume({
    required DateTime? start,
    required DateTime? end,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dailyVolume,
          [],
          {
            #start: start,
            #end: end,
          },
        ),
        returnValue: _i5.Future<List<({DateTime day, int volume})>>.value(
            <({DateTime day, int volume})>[]),
      ) as _i5.Future<List<({DateTime day, int volume})>>);

  @override
  _i5.Future<List<_i2.Template>> listTemplates() => (super.noSuchMethod(
        Invocation.method(
          #listTemplates,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Template>>.value(<_i2.Template>[]),
      ) as _i5.Future<List<_i2.Template>>);

  @override
  _i5.Future<String> saveWorkoutAsTemplate({
    required String? workoutId,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWorkoutAsTemplate,
          [],
          {
            #workoutId: workoutId,
            #name: name,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #saveWorkoutAsTemplate,
            [],
            {
              #workoutId: workoutId,
              #name: name,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> createWorkoutFromTemplate({
    required String? templateId,
    String? title,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorkoutFromTemplate,
          [],
          {
            #templateId: templateId,
            #title: title,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createWorkoutFromTemplate,
            [],
            {
              #templateId: templateId,
              #title: title,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> createWorkoutFromTemplateAt({
    required String? templateId,
    required DateTime? date,
    String? title,
    bool? done = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorkoutFromTemplateAt,
          [],
          {
            #templateId: templateId,
            #date: date,
            #title: title,
            #done: done,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createWorkoutFromTemplateAt,
            [],
            {
              #templateId: templateId,
              #date: date,
              #title: title,
              #done: done,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> createTemplate({required String? name}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTemplate,
          [],
          {#name: name},
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createTemplate,
            [],
            {#name: name},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> setTemplateExercises({
    required String? templateId,
    required List<String>? exerciseIdsInOrder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTemplateExercises,
          [],
          {
            #templateId: templateId,
            #exerciseIdsInOrder: exerciseIdsInOrder,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> saveTemplateFromExercises({
    required String? name,
    required List<String>? exerciseIdsInOrder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTemplateFromExercises,
          [],
          {
            #name: name,
            #exerciseIdsInOrder: exerciseIdsInOrder,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #saveTemplateFromExercises,
            [],
            {
              #name: name,
              #exerciseIdsInOrder: exerciseIdsInOrder,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<double?> bestE1RMForExercise(String? exerciseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #bestE1RMForExercise,
          [exerciseId],
        ),
        returnValue: _i5.Future<double?>.value(),
      ) as _i5.Future<double?>);

  @override
  _i5.Future<
          ({DateTime date, double e1rm, _i2.SetEntry set, String workoutId})?>
      bestE1RMEntry(String? exerciseId) => (super.noSuchMethod(
            Invocation.method(
              #bestE1RMEntry,
              [exerciseId],
            ),
            returnValue: _i5.Future<
                ({
                  DateTime date,
                  double e1rm,
                  _i2.SetEntry set,
                  String workoutId
                })?>.value(),
          ) as _i5.Future<
              ({
                DateTime date,
                double e1rm,
                _i2.SetEntry set,
                String workoutId
              })?>);

  @override
  _i5.Future<List<({DateTime day, double volume})>> exerciseVolumeSeries({
    required String? exerciseId,
    required DateTime? start,
    required DateTime? end,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exerciseVolumeSeries,
          [],
          {
            #exerciseId: exerciseId,
            #start: start,
            #end: end,
          },
        ),
        returnValue: _i5.Future<List<({DateTime day, double volume})>>.value(
            <({DateTime day, double volume})>[]),
      ) as _i5.Future<List<({DateTime day, double volume})>>);

  @override
  _i5.Future<({double e1rm, bool isPr})> checkIfNewPR({
    required String? exerciseId,
    required int? reps,
    required double? weight,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkIfNewPR,
          [],
          {
            #exerciseId: exerciseId,
            #reps: reps,
            #weight: weight,
          },
        ),
        returnValue: _i5.Future<({double e1rm, bool isPr})>.value(
            (e1rm: 0.0, isPr: false)),
      ) as _i5.Future<({double e1rm, bool isPr})>);

  @override
  _i5.Future<bool> hasAnyPRInWorkout(String? workoutId) => (super.noSuchMethod(
        Invocation.method(
          #hasAnyPRInWorkout,
          [workoutId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<double?> bestE1rmForExerciseBefore({
    required String? exerciseId,
    required int? beforeEpoch,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #bestE1rmForExerciseBefore,
          [],
          {
            #exerciseId: exerciseId,
            #beforeEpoch: beforeEpoch,
          },
        ),
        returnValue: _i5.Future<double?>.value(),
      ) as _i5.Future<double?>);

  @override
  _i5.Future<_i6.WorkoutWithDetails> getWorkoutWithDetails(String? workoutId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutWithDetails,
          [workoutId],
        ),
        returnValue:
            _i5.Future<_i6.WorkoutWithDetails>.value(_FakeWorkoutWithDetails_26(
          this,
          Invocation.method(
            #getWorkoutWithDetails,
            [workoutId],
          ),
        )),
      ) as _i5.Future<_i6.WorkoutWithDetails>);

  @override
  _i5.Future<List<_i6.WorkoutWithDetails>> getMultipleWorkoutsWithDetails(
          List<String>? workoutIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMultipleWorkoutsWithDetails,
          [workoutIds],
        ),
        returnValue: _i5.Future<List<_i6.WorkoutWithDetails>>.value(
            <_i6.WorkoutWithDetails>[]),
      ) as _i5.Future<List<_i6.WorkoutWithDetails>>);
}
